# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c9cc41813f5e069132ad793f3c3d0ab74b865417a5301f8f807cd9a5ef7491fa2c8b5aa0c4cbdd5f5144de8a29c3d2b8b768c9dc6b61f35183e05a148bd7285

test:
  secret_key_base: 578cec1f984afbf0d777d0768219433f0474c015bb7123d3f0760d158fbe7080535a6dd6e57d8f2f7bbe3a377728b093f49b7c8fd749be857ae14e4af2b79e55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
